# Generated by Django 5.2.1 on 2026-02-20 06:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('identification_number', models.CharField(db_index=True, help_text='Student ID, Employee ID, etc.', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encoding', models.BinaryField(blank=True, help_text='Serialized numpy array of face encoding', null=True)),
                ('image_path', models.CharField(blank=True, help_text='Path to the original image file', max_length=500, null=True)),
                ('image_hash', models.CharField(blank=True, help_text='SHA-256 hash for duplicate detection', max_length=64, null=True, unique=True)),
                ('quality_score', models.FloatField(blank=True, help_text='Image quality metric (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_primary', models.BooleanField(default=False, help_text='Primary encoding for this person')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='recognition.person')),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
                'db_table': 'face_encodings',
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosters_created', to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(blank=True, help_text='People expected to be in this roster', related_name='rosters', to='recognition.person')),
            ],
            options={
                'verbose_name': 'Roster',
                'verbose_name_plural': 'Rosters',
                'db_table': 'rosters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_type', models.CharField(blank=True, help_text='e.g., class, meeting, event (deprecated, use roster instead)', max_length=50, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('expected_count', models.IntegerField(blank=True, help_text='Expected number of attendees', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL)),
                ('roster', models.ForeignKey(blank=True, help_text='Roster of expected people for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='recognition.roster')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RosterAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], db_index=True, help_text='Attendance status', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, help_text='Time when person was marked/recognized', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(help_text='Person from the roster', on_delete=django.db.models.deletion.CASCADE, related_name='roster_attendance_records', to='recognition.person')),
                ('roster', models.ForeignKey(help_text='Roster this attendance record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='recognition.roster')),
                ('session', models.ForeignKey(help_text='Session this attendance is for', on_delete=django.db.models.deletion.CASCADE, related_name='roster_attendance_records', to='recognition.session')),
            ],
            options={
                'verbose_name': 'Roster Attendance',
                'verbose_name_plural': 'Roster Attendances',
                'db_table': 'roster_attendance',
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recognized_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField(blank=True, help_text='Recognition confidence (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('image_path', models.CharField(blank=True, help_text='Path to the captured image', max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Manual verification flag')),
                ('notes', models.TextField(blank=True, null=True)),
                ('face_encoding_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognitions', to='recognition.faceencoding')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='recognition.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='recognition.session')),
            ],
            options={
                'verbose_name': 'Recognition',
                'verbose_name_plural': 'Recognitions',
                'db_table': 'recognitions',
                'ordering': ['-recognized_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('face_detected', 'Face Detected'), ('face_recognized', 'Face Recognized'), ('unknown_face', 'Unknown Face'), ('attendance_marked', 'Attendance Marked'), ('manual_override', 'Manual Override'), ('session_started', 'Session Started'), ('session_ended', 'Session Ended')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recognition.session')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], db_index=True, max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='recognition.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='recognition.session')),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'db_table': 'attendance_summary',
            },
        ),
        migrations.CreateModel(
            name='UnidentifiedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropped_face', models.ImageField(blank=True, null=True, upload_to='unidentified/cropped/')),
                ('full_frame', models.ImageField(blank=True, null=True, upload_to='unidentified/full/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_faces', to='recognition.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], name='persons_first_n_94c600_idx'),
        ),
        migrations.AddIndex(
            model_name='faceencoding',
            index=models.Index(fields=['person', 'is_primary'], name='face_encodi_person__e61b87_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterattendance',
            index=models.Index(fields=['session', 'status'], name='roster_atte_session_66367e_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterattendance',
            index=models.Index(fields=['roster', 'session'], name='roster_atte_roster__ff7bb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rosterattendance',
            unique_together={('roster', 'session', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='recognition',
            unique_together={('session', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('session', 'person')},
        ),
    ]
