# Generated by Django 5.2.1 on 2025-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unidentifiedface',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
