# Generated by Codex on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
    ]
