services:
  reconroll-db:
    image: postgres:15
    container_name: reconroll-db
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
       - prod_db_data:/var/lib/postgresql/data

  reconroll:
    image: fastundra/reconroll:latest
    container_name: reconroll
    ports:
      - "80:8000"
    volumes:
      - ./app:/app
      - static_volume:/vol/static
      - media_volume:/vol/media
      - ./scripts/scripts.sh:/scripts/scripts.sh

      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${SOCKET_PATH:-/tmp/.X11-unix}:/tmp/.X11-unix
    env_file:
      - .env.prod
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    command: sh -c "/scripts/scripts.sh"
    depends_on:
      - reconroll-db
    stdin_open: true
    tty: true
    privileged: true
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  prod_db_data:
